package com.fnbx.cashclose.entity;

import com.fnbx.cashclose.enums.FundPeriod;
import com.fnbx.cashclose.enums.FundStatus;
import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * A fund withdrawal - the owner taking accumulated cash out of a branch drawer.
 *
 * <h2>Different grain from everything else in this schema</h2>
 * {@link CashClose} and its children are per shift. This is per branch and per
 * PERIOD ({@link #periodFrom}..{@link #periodTo}), spanning many shifts, often a
 * whole month. It therefore has no {@code cashCloseId} and is not governed by
 * {@code fn_close_child_guard}.
 *
 * <h2>Three figures, and the third is the point</h2>
 * <table>
 *   <caption>System versus reality</caption>
 *   <tr><th>Column</th><th>Where it comes from</th></tr>
 *   <tr><td>{@link #systemWithdrawAmount}</td>
 *       <td>Summed by the system from approved closes in the period</td></tr>
 *   <tr><td>{@link #actualReceivedAmount}</td>
 *       <td>Typed in from the bank statement or the cash actually received</td></tr>
 *   <tr><td>{@link #varianceAmount}</td>
 *       <td>Generated by PostgreSQL: {@code actual - system}</td></tr>
 * </table>
 *
 * <p>A non-zero variance means cash went missing <b>in transit</b> between the
 * branch drawer and the owner - a loss no individual close can reveal, because
 * each shift balances on its own. In Comfy's real data one branch matched exactly
 * (6,250,000 = 3,100,000 + 3,150,000) while another was off by 1,400,000.
 *
 * <p>The {@code EXCLUDE USING gist} constraint stops two live withdrawals for the
 * same branch covering overlapping periods; without it the same window could be
 * drawn twice and nothing would reconcile.
 */
@Entity
@Table(schema = "cashclose", name = "fund_withdrawal")
@Getter
@Setter
@NoArgsConstructor
public class FundWithdrawal {

    @Id
    @Column(name = "fund_withdrawal_id")
    private UUID fundWithdrawalId;

    @Column(name = "fund_withdrawal_code", nullable = false)
    private String fundWithdrawalCode;

    /** Immutable after insert. */
    @Column(name = "business_id", nullable = false, updatable = false)
    private UUID businessId;

    @Column(name = "branch_id", nullable = false)
    private UUID branchId;

    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Enumerated(EnumType.STRING)
    @Column(name = "period_type", nullable = false, columnDefinition = "shared.fund_period")
    private FundPeriod periodType;

    @Column(name = "period_from", nullable = false) private LocalDate periodFrom;
    @Column(name = "period_to", nullable = false)   private LocalDate periodTo;

    @Column(name = "created_by", nullable = false)  private UUID createdBy;

    /** Accumulated cash before this withdrawal. */
    @Column(name = "system_pot_before", nullable = false)
    private BigDecimal systemPotBefore = BigDecimal.ZERO;

    /** What the system totalled from the closes in this period. */
    @Column(name = "system_withdraw_amount", nullable = false)
    private BigDecimal systemWithdrawAmount = BigDecimal.ZERO;

    /** Typed in from the statement - not derivable from any table. */
    @Column(name = "actual_received_amount", nullable = false)
    private BigDecimal actualReceivedAmount = BigDecimal.ZERO;

    /** Generated in the database: {@code actualReceivedAmount - systemWithdrawAmount}. */
    @Setter(AccessLevel.NONE)
    @Column(name = "variance_amount", insertable = false, updatable = false)
    private BigDecimal varianceAmount;

    @Column(name = "system_pot_after", nullable = false)
    private BigDecimal systemPotAfter = BigDecimal.ZERO;

    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, columnDefinition = "shared.fund_status")
    private FundStatus status = FundStatus.OPEN;

    @Column(name = "note") private String note;

    @Setter(AccessLevel.NONE)
    @Column(name = "created_at", insertable = false, updatable = false) private Instant createdAt;

    @Setter(AccessLevel.NONE)
    @Column(name = "updated_at", insertable = false, updatable = false) private Instant updatedAt;

    /** The database also enforces this with a CHECK. */
    public boolean periodIsValid() {
        return periodFrom != null && periodTo != null && !periodTo.isBefore(periodFrom);
    }

    /**
     * Whether system and actual disagree. Non-zero is a signal to investigate,
     * not a data-entry error - review each close in the period before concluding.
     */
    public boolean hasVariance() {
        return varianceAmount != null && varianceAmount.signum() != 0;
    }
}
