package com.fnbx.identity.dto.request;

import com.fnbx.shared.enums.BusinessType;
import jakarta.validation.constraints.*;

/** Submit an application using the verification token bound to ownerEmail. Codes are generated by the backend. */
public record BusinessRegistrationRequest(
        @NotBlank @Size(max = 200) String businessName,
        BusinessType businessType,
        @Size(min = 3, max = 3) @Pattern(regexp = "^[A-Za-z]{3}$") String currencyCode,
        @Size(max = 64) String timezone,
        @NotBlank @Size(max = 200) String branchName,
        @Size(max = 500) String branchAddress,
        @NotBlank @Email @Size(max = 255) String ownerEmail,
        @NotBlank @Size(max = 200) String ownerFirstName,
        @NotBlank @Size(max = 200) String ownerLastName,
        @Size(max = 30) String ownerPhone,
        @NotBlank @Size(max = 128) String registrationToken) {}
