package com.fnbx.platform.enums;

public enum MovementKindCode {
    EXPENSE_SUPPLY,
    EXPENSE_SHIPPING,
    EXPENSE_MAINTENANCE,
    EXPENSE_UTILITY,
    EXPENSE_OTHER,
    EOD_STAFF_PARKING,
    EOD_EXPENSE_OTHER,
    CHANGE_FUND_IN,
    CHANGE_FUND_OUT,
    DRAWER_BORROW,
    STAFF_REIMBURSE,
    UNPAID_BILL,
    POS_ERROR,
    MISCOUNT,
    THEFT_SUSPECTED,
    TIPS,
    EXPENSE_REFUND,
    EXPENSE_STAFF_PARKING,
    EXPLANATION_OTHER
}
