package com.fnbx.cashclose.mapper;

import com.fnbx.cashclose.dto.response.CashCloseResponse;
import com.fnbx.cashclose.dto.response.CashMovementResponse;
import com.fnbx.cashclose.dto.response.CloseDecisionResponse;
import com.fnbx.cashclose.dto.response.MovementKindResponse;
import com.fnbx.cashclose.dto.response.MovementDecisionResponse;
import com.fnbx.cashclose.entity.CashClose;
import com.fnbx.cashclose.entity.CashCloseCalc;
import com.fnbx.cashclose.entity.CashCloseDecision;
import com.fnbx.cashclose.entity.CashMovement;
import com.fnbx.cashclose.entity.CashMovementDecision;
import com.fnbx.cashclose.service.CashCloseView;
import com.fnbx.platform.entity.MovementKind;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

import java.math.BigDecimal;
import java.util.List;

/**
 * Entity to DTO mapping. Generated at compile time by MapStruct - the generated
 * class is plain Java, no reflection, no proxies.
 *
 * <h2>Why MapStruct does not weaken the API contract</h2>
 * The worry is that automatic name matching couples the DTO to the entity, so
 * renaming a column silently reshapes the API. The opposite is true, because of
 * one setting in the parent POM:
 *
 * <pre>-Amapstruct.unmappedTargetPolicy=ERROR</pre>
 *
 * Rename {@code CashClose.userId} to {@code staffId} while the DTO still says
 * {@code userId}, and the <b>build fails</b>:
 * {@code Unmapped target property: "userId"}. It cannot ship a null field to a
 * client. From there you have two visible choices, both in the diff:
 *
 * <ul>
 *   <li>add {@code @Mapping(source = "staffId", target = "userId")} - the entity
 *       moved, the contract held. This is almost always right.</li>
 *   <li>rename the DTO field - a deliberate breaking API change, which belongs in
 *       a version bump.</li>
 * </ul>
 *
 * <p>What MapStruct cannot protect against is naming DTO fields after entity
 * fields <i>on purpose</i> so renames "just propagate". That is a review habit,
 * not a tool setting: <b>DTO names belong to clients, not to the schema.</b>
 *
 * <h2>Why one method is hand-written</h2>
 * {@link #toResponse(CashCloseView)} assembles from three sources - the entity,
 * the calculated view, and the derived risk level - and has to coalesce nulls
 * while a close is still an empty draft. Expressing that as fifteen
 * {@code @Mapping} lines would be longer and harder to read than the Java. The
 * simple one-to-one mappings below are where MapStruct earns its keep.
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface CashCloseMapper {

    // ------------------------------------------------------------------
    // Generated by MapStruct
    // ------------------------------------------------------------------

    /**
     * A ledger line plus the catalogue entry that gives it meaning.
     *
     * <p>{@code kind} is a second source parameter: {@code kindCode} and
     * {@code kindDisplayName} come from it, everything else from the movement.
     */
    @Mapping(target = "effectType",      source = "movement.effectType")
    @Mapping(target = "kindCode",        source = "kind.kindCode")
    @Mapping(target = "kindDisplayName", source = "kind.displayName")
    @Mapping(target = "absAmount",       expression = "java(movement.absAmount())")
    CashMovementResponse toResponse(CashMovement movement, MovementKind kind);

    @Mapping(target = "absAmount", expression = "java(decision.absAmount())")
    MovementDecisionResponse toResponse(CashMovementDecision decision);

    /**
     * One catalogue entry for the entry dropdown.
     *
     * <p>Every field of the response exists on {@code MovementKind} under the same
     * name, so there is nothing to spell out here - and if somebody renames one,
     * {@code unmappedTargetPolicy=ERROR} fails the build rather than shipping a null
     * to the client. {@code kindSk}, {@code validFrom}, {@code validTo} and
     * {@code businessId} are deliberately NOT on the response: a surrogate key and a
     * version window are how the server picks the row, not something a client should
     * ever send back.
     */
    MovementKindResponse toResponse(MovementKind kind);

    List<MovementKindResponse> toMovementKindList(List<MovementKind> kinds);

    CloseDecisionResponse toResponse(CashCloseDecision decision);

    List<MovementDecisionResponse> toMovementDecisionList(List<CashMovementDecision> decisions);

    List<CloseDecisionResponse> toCloseDecisionList(List<CashCloseDecision> decisions);

    // ------------------------------------------------------------------
    // Hand-written: three sources, and nulls while the close is an empty draft
    // ------------------------------------------------------------------

    default CashCloseResponse toResponse(CashCloseView view) {
        CashClose c = view.close();
        CashCloseCalc k = view.calc();

        return CashCloseResponse.builder()
                .cashCloseId(c.getCashCloseId())
                .cashCloseCode(c.getCashCloseCode())
                .branchId(c.getBranchId())
                .shiftTypeId(c.getShiftTypeId())
                .businessDate(c.getBusinessDate())

                .status(c.getStatus().name())
                .riskLevel(view.riskLevel() == null ? null : view.riskLevel().name())
                .late(c.isLate())
                .calcVersion(c.getCalcVersion())

                .posExpectedCash(c.getPosExpectedCash())
                .expectedCashSource(c.getExpectedCashSource().name())
                .expectedCashLocked(c.isExpectedCashLocked())

                .countedCash(nz(k == null ? null : k.getCountedCash()))
                .cashDifference(nz(k == null ? null : k.getCashDifference()))
                .explainedDifference(nz(k == null ? null : k.getExplainedDifference()))
                .pendingDifference(nz(k == null ? null : k.getPendingDifference()))
                .unexplainedDifference(nz(k == null ? null : k.getUnexplainedDifference()))
                .expenseTotal(nz(k == null ? null : k.getExpenseTotal()))
                .cashOutTotal(nz(k == null ? null : k.getCashOutTotal()))
                .cashInTotal(nz(k == null ? null : k.getCashInTotal()))
                .tipsTotal(nz(k == null ? null : k.getTipsTotal()))
                .tipsInDrawerTotal(nz(k == null ? null : k.getTipsInDrawerTotal()))
                .withdrawalAmount(c.getWithdrawalAmount())
                .cashRemaining(nz(k == null ? null : k.getCashRemaining()))

                .appliedDiffAllowedAbs(c.getAppliedDiffAllowedAbs())
                .appliedDiffAlertAbs(c.getAppliedDiffAlertAbs())

                .note(c.getNote())
                .createdBy(c.getCreatedBy())
                .createdAt(c.getCreatedAt())
                .submittedAt(c.getSubmittedAt())
                .approvedBy(view.approvedBy())
                .approvedAt(view.approvedAt())
                .build();
    }

    /** A draft with no lines yet has no calculated row; report zero, not null. */
    private static BigDecimal nz(BigDecimal v) {
        return v == null ? BigDecimal.ZERO : v;
    }
}
