-- ============================================================================
-- 003 PLATFORM (CORE) - business parameters, audit trail, lookup catalogues
--
-- Holds NO technical configuration (DB URLs, API keys, buckets). Those live in
-- the backend's environment variables. The distinction that matters: things the
-- owner can change without a deploy go here; things only a developer changes do not.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- denomination - bank notes and coins. Global, not tenant-scoped, so no
-- business_id and no RLS.
-- ----------------------------------------------------------------------------
CREATE TABLE platform.denomination (
  denomination_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  currency_code   CHAR(3) NOT NULL DEFAULT 'VND',
  face_value      shared.d_money_nonneg NOT NULL CHECK (face_value > 0),
  is_active       BOOLEAN NOT NULL DEFAULT true,
  UNIQUE (currency_code, face_value)
);

-- ============================================================================
-- movement_kind - THE catalogue behind the cash ledger
--
-- Replaces three former tables: cash_movement_type + expense_category +
-- cash_diff_reason.
--
-- WHY MERGED: in Comfy's real data, 260 of 311 cash_diff_explanation rows were
-- verbatim copies of a cash_movement row - same amount, note reading "auto from
-- expense: ...", and a reason_code mechanically derived from the category
-- (SUPPLY -> SUPPLY_NOT_IN_POS). Two tables, one fact. Merged, there is nothing
-- left to disagree.
--
-- THE TWO ANALYTIC AXES ARE NOT LOST - they move up to this dimension:
--   expense_category  : "what was it spent on"       (expense report)
--   diff_reason_group : "why the drawer differs"     (shortage report)
-- The fact row carries a single key, kind_sk. Standard star schema.
--
-- THREE FLAGS THAT DECIDE THE ARITHMETIC. They are NOT on the fact row: they
-- depend on kind_code, not on the row's key, so storing them there breaks 3NF.
--   effect_type        : did cash actually move, and which way
--   affects_difference : was this already inside counted_cash at count time
--   affects_remaining  : does this leave the drawer before hand-over
--
-- Why effect_type must be separate: 21 of 51 manual explanations in the real data
-- were MISCOUNT / POS_ERROR / UNPAID_BILL - no cash moved at all. Without the
-- distinction, summing by cash direction stops meaning "money spent" and the
-- expense report is inflated by keying mistakes.
--
-- SCD-2: changing a business rule means inserting a NEW VERSION
-- (valid_from/valid_to), never updating the old row. A fact points at the kind_sk
-- of the version in force when it happened, so a close approved in 2026 is never
-- recomputed under a 2027 rule. See 007-cashclose/002-integrity.sql section 13.6.
--
-- business_id NULL = global default; non-null = tenant-specific.
-- ============================================================================
CREATE TABLE platform.movement_kind (
  kind_sk           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  kind_code         TEXT NOT NULL,
  business_id       UUID REFERENCES identity.business(business_id),

  -- SCD-2
  valid_from        DATE NOT NULL DEFAULT DATE '2000-01-01',
  valid_to          DATE,                       -- NULL = still in force

  -- the three flags that decide the arithmetic
  effect_type       TEXT    NOT NULL
                      CHECK (effect_type IN ('CASH_OUT','CASH_IN','NO_CASH_FLOW')),
  affects_difference BOOLEAN NOT NULL,
  affects_remaining  BOOLEAN NOT NULL,

  -- the two analytic axes
  expense_category  TEXT,
  diff_reason_group TEXT,

  requires_receipt  BOOLEAN NOT NULL DEFAULT false,
  requires_note     BOOLEAN NOT NULL DEFAULT false,
  display_name      TEXT NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  CHECK (valid_to IS NULL OR valid_to > valid_from),

  -- Target for the COMPOSITE FK from cash_movement: the effect_type on a fact row
  -- cannot disagree with its kind. See ck_movement_sign in 007.
  UNIQUE (kind_sk, effect_type),

  -- no two versions of the same kind (same tenant) may overlap in time
  EXCLUDE USING gist (
    kind_code WITH =,
    (COALESCE(business_id,'00000000-0000-0000-0000-000000000000'::uuid)) WITH =,
    daterange(valid_from, valid_to) WITH &&
  )
);
CREATE INDEX idx_movement_kind_code ON platform.movement_kind (kind_code, business_id);

-- effect_type MUST stay constant across versions of one kind_code. If "supply
-- purchase" flipped from CASH_OUT to CASH_IN it would be a different concept and
-- needs a different kind_code - otherwise GROUP BY kind_code in a report would
-- add two opposite directions together.
CREATE FUNCTION platform.fn_movement_kind_effect_stable() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE v_prev TEXT;
BEGIN
  SELECT effect_type INTO v_prev
    FROM platform.movement_kind
   WHERE kind_code = NEW.kind_code
     AND business_id IS NOT DISTINCT FROM NEW.business_id
     AND kind_sk <> COALESCE(NEW.kind_sk, -1)
   LIMIT 1;
  IF v_prev IS NOT NULL AND v_prev <> NEW.effect_type THEN
    RAISE EXCEPTION
      'kind % da co effect_type=% o phien ban khac; effect_type bat bien — hay dat kind_code moi',
      NEW.kind_code, v_prev;
  END IF;
  RETURN NEW;
END $fn$;
CREATE TRIGGER trg_movement_kind_effect_stable
  BEFORE INSERT OR UPDATE ON platform.movement_kind
  FOR EACH ROW EXECUTE FUNCTION platform.fn_movement_kind_effect_stable();

-- Resolve the version in force on the close's BUSINESS DATE, not now(): a 15 Jun
-- close submitted late on 17 Jun still follows the 15 Jun rules. Tenant-specific
-- entries win over global defaults.
CREATE FUNCTION platform.fn_movement_kind_at(
  p_kind_code TEXT, p_business_id UUID, p_on DATE)
RETURNS BIGINT LANGUAGE sql STABLE AS $fn$
  SELECT k.kind_sk
  FROM platform.movement_kind k
  WHERE k.kind_code = p_kind_code
    AND (k.business_id = p_business_id OR k.business_id IS NULL)
    AND p_on >= k.valid_from
    AND (k.valid_to IS NULL OR p_on < k.valid_to)
  ORDER BY (k.business_id IS NULL)          -- rieng tenant truoc, toan cuc sau
  LIMIT 1;
$fn$;

-- ----------------------------------------------------------------------------
-- app_config - BUSINESS parameters the owner can change without a deploy
--
-- Resolution order: BRANCH beats BUSINESS beats GLOBAL (see fn_config_num).
--
-- No history is kept here. Instead each cash_close SNAPSHOTS the thresholds that
-- judged it, and every change is written to audit_log by a trigger. That way
-- raising a threshold next year cannot silently re-grade last year's closes.
-- ----------------------------------------------------------------------------
CREATE TABLE platform.app_config (
  config_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  scope        shared.config_scope NOT NULL DEFAULT 'GLOBAL',
  business_id  UUID REFERENCES identity.business(business_id),
  branch_id    UUID REFERENCES identity.branch(branch_id),
  config_key   TEXT NOT NULL,
  config_value JSONB,
  description  TEXT,
  updated_by   UUID,
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (
    (scope = 'GLOBAL'   AND business_id IS NULL     AND branch_id IS NULL) OR
    (scope = 'BUSINESS' AND business_id IS NOT NULL AND branch_id IS NULL) OR
    (scope = 'BRANCH'   AND branch_id   IS NOT NULL)
  )
);
CREATE UNIQUE INDEX uq_config_key ON platform.app_config (
  config_key,
  COALESCE(business_id,'00000000-0000-0000-0000-000000000000'::uuid),
  COALESCE(branch_id,  '00000000-0000-0000-0000-000000000000'::uuid)
);
CREATE TRIGGER trg_config_touch BEFORE UPDATE ON platform.app_config
  FOR EACH ROW EXECUTE FUNCTION shared.fn_touch_updated_at();

-- Resolve a numeric parameter: BRANCH -> BUSINESS -> GLOBAL
CREATE FUNCTION platform.fn_config_num(p_branch UUID, p_key TEXT)
RETURNS NUMERIC LANGUAGE sql STABLE AS $fn$
  SELECT (c.config_value #>> '{}')::numeric
  FROM platform.app_config c
  LEFT JOIN identity.branch b ON b.branch_id = p_branch
  WHERE c.config_key = p_key
    AND (c.scope = 'GLOBAL'
      OR (c.scope = 'BUSINESS' AND c.business_id = b.business_id)
      OR (c.scope = 'BRANCH'   AND c.branch_id   = p_branch))
  ORDER BY CASE c.scope WHEN 'BRANCH' THEN 1 WHEN 'BUSINESS' THEN 2 ELSE 3 END
  LIMIT 1;
$fn$;

-- ----------------------------------------------------------------------------
-- audit_log - ONLY events that have no business table of their own
--
--   LOGIN_SUCCESS / LOGIN_FAILED / ACCOUNT_LOCKED
--   CONFIG_CREATED / CONFIG_CHANGED / CONFIG_DELETED   (written by trigger)
--   ROLE_GRANTED / ROLE_REVOKED                        (written by trigger)
--   CASH_CLOSE_VOIDED, DATA_EXPORTED, USER_CREATED / DEACTIVATED
--
-- Cash close status changes are NOT written here - they live in
-- cashclose.cash_close_decision, which carries action/old_status/new_status.
-- Application and debug logs are not written here either - those belong in
-- Datadog/ELK. This table is for auditors, not developers.
-- ----------------------------------------------------------------------------
CREATE TABLE platform.audit_log (
  log_id        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  business_id   UUID,
  occurred_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  actor_user_id UUID,
  actor_name    TEXT,
  action        TEXT NOT NULL,
  entity_type   TEXT NOT NULL,
  entity_id     TEXT,
  old_value     JSONB,
  new_value     JSONB,
  ip_address    INET,
  user_agent    TEXT
);
CREATE INDEX idx_audit_entity ON platform.audit_log (business_id, entity_type, entity_id);
CREATE INDEX idx_audit_time   ON platform.audit_log (business_id, occurred_at DESC);
CREATE INDEX idx_audit_actor  ON platform.audit_log (actor_user_id, occurred_at DESC);

-- Append-only at BOTH layers: the trigger AND the revoked grant (see 910-roles).
-- They complement each other - a trigger can be disabled by anyone with the
-- privilege, a grant cannot.
CREATE TRIGGER trg_audit_append_only BEFORE UPDATE OR DELETE ON platform.audit_log
  FOR EACH ROW EXECUTE FUNCTION shared.fn_forbid_mutation();

-- ----------------------------------------------------------------------------
-- A config change is security data, so it is recorded at the DB layer where the
-- backend cannot "forget" to log it.
-- ----------------------------------------------------------------------------
CREATE FUNCTION platform.fn_audit_config_change() RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  INSERT INTO platform.audit_log (business_id, actor_user_id, action, entity_type, entity_id, old_value, new_value)
  VALUES (
    COALESCE(NEW.business_id, OLD.business_id),
    COALESCE(NEW.updated_by, OLD.updated_by),
    CASE TG_OP WHEN 'INSERT' THEN 'CONFIG_CREATED'
               WHEN 'UPDATE' THEN 'CONFIG_CHANGED'
               ELSE 'CONFIG_DELETED' END,
    'app_config',
    COALESCE(NEW.config_key, OLD.config_key),
    CASE WHEN TG_OP = 'INSERT' THEN NULL
         ELSE jsonb_build_object('value', OLD.config_value, 'scope', OLD.scope,
                                 'business_id', OLD.business_id, 'branch_id', OLD.branch_id) END,
    CASE WHEN TG_OP = 'DELETE' THEN NULL
         ELSE jsonb_build_object('value', NEW.config_value, 'scope', NEW.scope,
                                 'business_id', NEW.business_id, 'branch_id', NEW.branch_id) END
  );
  RETURN NULL;
END $fn$;
CREATE TRIGGER trg_config_audit AFTER INSERT OR UPDATE OR DELETE ON platform.app_config
  FOR EACH ROW EXECUTE FUNCTION platform.fn_audit_config_change();

-- Granting and revoking roles is security data too.
CREATE FUNCTION platform.fn_audit_role_change() RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  INSERT INTO platform.audit_log (business_id, action, entity_type, entity_id, old_value, new_value)
  VALUES (
    COALESCE(NEW.business_id, OLD.business_id),
    CASE WHEN TG_OP = 'INSERT' THEN 'ROLE_GRANTED'
         WHEN TG_OP = 'DELETE' THEN 'ROLE_REVOKED'
         WHEN NEW.revoked_at IS NOT NULL AND OLD.revoked_at IS NULL THEN 'ROLE_REVOKED'
         ELSE 'ROLE_CHANGED' END,
    'staff_branch_role',
    COALESCE(NEW.staff_id, OLD.staff_id)::text,
    CASE WHEN TG_OP = 'INSERT' THEN NULL
         ELSE jsonb_build_object('branch_id', OLD.branch_id, 'role', OLD.role, 'revoked_at', OLD.revoked_at) END,
    CASE WHEN TG_OP = 'DELETE' THEN NULL
         ELSE jsonb_build_object('branch_id', NEW.branch_id, 'role', NEW.role, 'revoked_at', NEW.revoked_at) END
  );
  RETURN NULL;
END $fn$;
CREATE TRIGGER trg_role_audit AFTER INSERT OR UPDATE OR DELETE ON identity.staff_branch_role
  FOR EACH ROW EXECUTE FUNCTION platform.fn_audit_role_change();
